set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

colorscheme desert
set autoindent
set number
syntax enable
syntax on
call pathogen#infect()



"设置内核为UTF-8
"set enc=utf-8
"设置解码顺序,这个顺序经测试可以很好的识别UTF-8,JIS,GBK
"set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936


"搜索忽略大小写  
set ignorecase

"禁止生成临时文件 
set nobackup  

"语言设置  
"set langmenu=zh_CN.UTF-8  
"language message zh_CN.UTF-8  
"set guifont=NSimSun:h10  
"set guifont=Courier_New:h12:cANSI
set guifont=黑体:h14:cANSI
set guifontwide=黑体:h12:cGB2312

set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1

if has("win32")
set fileencoding=chinese
else
set fileencoding=utf-8
endif

"解决菜单乱码
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
"解决consle输出乱码
language messages zh_CN.utf-8



""""""""IME设置
"http://blog.csdn.net/lixiaodong037/article/details/6181531
"比较智能的设置，会记录输入法状态
set iminsert=0 imsearch=0
if has('multi_byte_ime')
	"未开启IME时光标背景色
	hi Cursor guifg=bg guibg=Orange gui=NONE
	"开启IME时光标背景色
	hi CursorIM guifg=NONE guibg=Skyblue gui=NONE
	" 关闭Vim的自动切换IME输入法(插入模式和检索模式)
	set iminsert=0 imsearch=0
	" 插入模式输入法状态未被记录时，默认关闭IME
	"inoremap <silent> <ESC> <ESC>:set iminsert=0<CR>
endif



""""""""latex suite 设置
set shellslash
set grepprg=grep\ -nH\ $*
filetype indent on
let g:tex_flavor='latex'
set sw=2
set iskeyword+=:
"下面这句是为了改掉每次输完｛｝自动加个<++>
"如果不改的化直接ctrl+j可以跳转到这里，然后会自动删除掉<++>
let g:Imap_UsePlaceHolders=0
"修改默认用xelatex编译
let g:Tex_CompileRule_pdf = 'xelatex --src-specials -interaction=nonstopmode $*'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_ViewRule_pdf = 'AcroRd32'




"设置comment方式，找了很久，呵呵
setlocal commentstring=<!--%s-->
setlocal comments=s:<!--,m:\ \ \ \ ,e:-->

let g:snips_author='songliheng'
